### ISSUE TITLE
make it possible to show banner on iOS versions > 6

### ISSUE THREAD

**Issue by Eschon** [patw0929/react-smartbanner#11]
I want to show a different app in the banner depending on the country the user is in. Since it is not possible for me to do this in the backend I have to change the meta tags with JavaScript.

This makes it impossible to use the native iOS banner but since your component ignores newer iOS versions I get no banner at all.

It would be nice if we had an option to allow the banner on newer iOS versions for use cases like mine.

**Comment by patw0929** [comment]
Merged your PR #12. Thanks a lot!
