### ISSUE TITLE
Error: cannot find module 'react-smartbanner'. 

### ISSUE THREAD

**Issue by sergesemashko** [patw0929/react-smartbanner#2]
It seems like NPM 2.0.0 package does not have `dist` folder - http://take.ms/6lEl2, and referenced file from `main` property of `package.json` is not found.

**Comment by omahlama** [comment]
The dist folder should be created in the `prepublish` hook, I'm guessing that something went wrong when this package was released to npm.

**Comment by patw0929** [comment]
Thanks for reporting this issue. 
I have fixed it in #3, and publish it as v2.0.1. I forget to put the `.npmignore` file.
Could you please help to verify it? Thank you!

**Comment by sergesemashko** [comment]
Thanks, that worked 👍
