### ISSUE TITLE
Uncaught exception in IE 10.

### ISSUE THREAD

**Issue by usandfriends** [patw0929/react-smartbanner#21]
https://github.com/patw0929/react-smartbanner/blob/master/src/components/SmartBanner.js#L27 references `window.navigator.language`, which is `undefined` in IE 10. This causes an uncaught exception and breaks our app.

**Comment by patw0929** [comment]
Hi @usandfriends,

Thanks for reporting this issue. 😄 
I made a fix PR #22, could you help me to verify the approach is working?

**Comment by usandfriends** [comment]
Yep, it looks good! Thanks for the quick turnaround.

**Comment by patw0929** [comment]
Fixed & published as v3.0.3.
