### ISSUE TITLE
iOS native smart banner shows on top of this smart banner

### ISSUE THREAD

**Issue by cdbean** [patw0929/react-smartbanner#23]
Safari has a built in feature that reads the same format meta tag and shows the smart banner. This causes the web to show two banners

https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/PromotingAppswithAppBanners/PromotingAppswithAppBanners.html

**Comment by patw0929** [comment]
I'm using iOS 10.3.3 & Safari, it seems ok, only the native smart banner shown up.
Could you provide more information about this issue? Thanks!

**Comment by cdbean** [comment]
I think the native smart banner should be disabled. Otherwise we will be seeing two banners, like below (using iPhone Safari):

![img_6642 png](https://user-images.githubusercontent.com/578035/29378119-c3a2ab1a-8272-11e7-856c-75d48e2f91e7.png)

This issue has been reported here as well: https://github.com/kudago/smart-app-banner/pull/60

**Comment by patw0929** [comment]
I'm curious about the smartbanner (js) is shown automatically? Or it's shown by clicking the `iOS` button? (force to change smartbanner type)

---

Related pr: #12

**Comment by cdbean** [comment]
Yes this `react-smartbanner` is shown by clicking the `iOS` button, and the native banner is shown automatically. I think when we want to show the `react-smartbanner`, the native banner should be disabled, right?

**Comment by patw0929** [comment]
I made a PR #24, could you help me to review? Thanks!
