### ISSUE TITLE
Bad or partial release

### ISSUE THREAD

**Issue by poorpaddy** [patw0929/react-smartbanner#33]
It looks like the dist files didn't get properly generated for v5.0.0. The `dist/main.js` file shows the old `this.props.url` and main.css isn't being generated at all.

Double checked clearing both npm & yarn cache and nuked node modules each time.

**Comment by d7laungani** [comment]
I have this issue as well and I am getting the latest release that your fix has. What do I do since main.js is showing up but the main.css is not being generated. Thanks.

**Comment by patw0929** [comment]
Hey guys, I've released fixed version v5.0.4.
Could you help to verify it? Thanks!

**Comment by poorpaddy** [comment]
Looks like it's creating the dist folder correctly now.
