### ISSUE TITLE
The "language" code in Apple App Store is incorrect

### ISSUE THREAD

**Issue by vince1995** [patw0929/react-smartbanner#39]
The url for the Apple App Store is NOT `https://itunes.apple.com/LANGUAGE_CODE/app/id`, it's `https://itunes.apple.com/COUNTRY_CODE/app/id`.

That means when the browsers language is English the link to the App Store will be `https://itunes.apple.com/en/app/id` but it should be `https://itunes.apple.com/us/app/id`, `https://itunes.apple.com/gb/app/id` or any other country code.

**Comment by patw0929** [comment]
Yup, so [in code](https://github.com/patw0929/react-smartbanner/blob/master/src/components/SmartBanner.js#L44), it tries to retrieve the browser language's last two character, e.g., en-`us`, en-`gb` and zh-`tw`.
Could you help to list the exception cases? And any advice?
Thanks!

**Comment by vince1995** [comment]
Ohhhhhh. You're right. But I think it's better to get the location by the IP address.
