### ISSUE TITLE
Doesn't bring up appropriate store on Kindle

### ISSUE THREAD

**Issue by grossmail1** [patw0929/react-smartbanner#4]
This module works great on iOS and android however, when a user clicks the link using Silk on their kindle they are directed to the google playstore.

We have added the `<meta name="kindle-fire-app" content="app-id=B00JMRGQHI">` tag that worked on our old app using the jquery based library.  Is there a specific prop I need to add to make this work with the Amazon store?

**Comment by grossmail1** [comment]
I created a PR that solves this issue
#5

**Comment by patw0929** [comment]
Thank you for your contribution! 
Merged your PR and published as v2.1.0.

**Comment by grossmail1** [comment]
looks good to me
