### ISSUE TITLE
Doesn't support React 16.8+

### ISSUE THREAD

**Issue by danew** [patw0929/react-smartbanner#49]
In React 16.3 aliases for the unsafe lifecycles were introduced and now as of React >16.8 we receive warnings each time one of these APIs are used.

Renaming them to their `UNSAFE_*` counterparts will resolve the warnings.

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

**Comment by patw0929** [comment]
Merged #50 and published as v5.1.4.
