### ISSUE TITLE
Chrome iOS

### ISSUE THREAD

**Issue by mikelambert** [patw0929/react-smartbanner#9]
This checks for iOS 6+, but doesn't check for Safari vs Chrome. So the banner is correctly hidden on newer versions of Safari (in favor of native banners), but I believe Chrome will also be hidden, right? Chrome doesn't support native app banners.

**Comment by Ardhimas** [comment]
I fixed this issue in a PR #13

**Comment by Ardhimas** [comment]
@patw0929 We can close this issue now, thanks for merging.

**Comment by patw0929** [comment]
Thank you! 👍
